= Modules et bibliothèques
ifndef::masterdoc[]
include::meta.adoc[]
include::attributes.adoc[]
endif::masterdoc[]

== Module
* Un _module_ est l'unité de base de décomposition d'un système
* Il permet d'organiser logiquement des modèles
* Un module s'appuie sur la notion d'_encapsulation_
** publie une interface, i.e. ce qui est accessible de l'extérieur
** utilise le principe de _masquage de l'information_, i.e. ce qui ne fait pas parti de l'interface est dissimulé
* Un module
** sert de brique de base pour la construction d'une architecture,
** représente le bon niveau de granularité pour la réutilisation,
** est un _espace de noms_ qui permet de gérer les conflits.
* La conception d'un module devrait conduire à un _couplage faible_ et une _forte cohésion_
couplage:: désigne l'importance des liaisons entre les éléments => *doit être réduit*
cohésion:: mesure le recouvrement entre un élément de conception et la tâche logique à accomplir => *doit être élevé*, i.e. chaque élément est responsable d'une tâche précise

.Exemple de modules dans une architecture multi-couches
[plantuml,package-diagram,png]
....
package Présentation {
    package "Interface Utilisateur"
    package "Logique de Présentation"
}

Présentation ..> Métier

package Métier {
    package "Façade"
    package "Entité"
    package "Logique"
}

Façade ..> Entité
Façade ..> Logique
Métier ..> Données

package "Données" {
    package "Accès aux Données"
    package "Accès aux services"
}

database SourcesdeDonnées
cloud ServicesExternes

Données ..> SourcesdeDonnées
Données -(0- ServicesExternes
....

== Module en Java
* Un module peut être représenté en Java en s'appuyant sur plusieurs aspects du langage :
** les _packages_,
** les http://tutorials.jenkov.com/java/modules.html[_modules_] depuis Java 9,
** les classes.

NOTE: Cette section n'aborde que la notion de _packages_.

== Définition d'un package
* Pour créer un package ou y ajouter une classe ou une interface, on place une instruction `package` au début du fichier source
+
[source,java,indent=0]
----
package monpackage;
----
* Tout ce qui est défini dans le fichier source fait alors partie du package
* Sans instruction de ce type, les éléments se trouvent dans le package _par défaut_ (non nommé)
* Les noms des package respectent en général une convention (par exemple, `fr.uvsq.monpackage`)
* La librairie Java est organisée de cette façon (`java.lang`, `java.util`, `java.io`, ...)

== Interface d'un package
* Seul les éléments publics sont accessibles à l'extérieur du package
* Pour rendre une classe ou une interface publique, on spécifie le mot-clé `public` dans sa déclaration
+
[source,java,indent=0]
----
public class MaClasse {
  //...
}
----

== Utilisation d'un package
* Différentes façons d'utiliser les éléments public d'un module
** utiliser son nom qualifié
+
[source,java,indent=0]
----
fr.uvsq.monpackage.MaClasse m = new fr.uvsq.monpackage.MaClasse();
----
** importer l'élément
+
[source,java,indent=0]
----
import fr.uvsq.monpackage.MaClasse; // en début de fichier source
----
** importer le module complet (déconseillé en général)
+
[source,java,indent=0]
----
import fr.uvsq.monpackage.*; // en début de fichier source
----
** importer les classes imbriquées
+
[source,java,indent=0]
----
import fr.uvsq.monpackage.MaClasse.*; // en début de fichier source
----
** importer les membres de classes
+
[source,java,indent=0]
----
import static fr.uvsq.monpackage.MaClasse.*; // en début de fichier source
----
* Les directives `import` se placent avant toute définition de classes ou d'interfaces mais après l'instruction `package`
* Deux packages sont automatiquement importés : le module par défaut et `java.lang`

== Package et gestion des sources en Java
* Dans un fichier source
** plusieurs éléments (classes, interfaces, ...) peuvent être définies
** un seul élément peut être `public`
** le nom de l'élément public doit être le même que le nom du fichier
* Parc convention, on se limite de préférence à une classe par fichier source
** le nom du fichier `.java` est le même que le nom de l'élément qu'il contient
* Le nom du répertoire doit refléter le nom du paquetage
** la classe `fr.uvsq.monpackage.MaClasse` doit se trouver dans le fichier `MaClasse.java` du répertoire `fr/uvsq/monpackage/`

== Package et compilation
* Lors de la compilation, un fichier `.class` est créé pour chaque élément source (classe, classe imbriquée, interface, ...)
* La hiérarchie de répertoires contenant les `.class` reflète les noms des modules
* Les répertoires où sont recherchées les classes lors de la compilation ou de l'exécution sont listés dans le _class path_
* Par défaut, le répertoire courant et la librairie Java se trouve dans le _class path_
* La façon dont le _class path_ est défini dépend de la plateforme
** en général, on définit une variable d'environnement `CLASSPATH`
* Le _class path_ contient des chemins vers des répertoires contenant une arborescence de `.class`, des fichiers `.jar`, des fichiers `.zip`

== Écosystème Java et bibliothèques
* L'écosystème Java fournit un nombre important de bibliothèques et d'outils de développement
* Dans un projet de développement logiciel, le choix des bibliothèques à utiliser est une étape importante
** fonctionnalités, complexité, support de la communauté, licence, ...
* La plupart des programmes Java font appel à des _bibliothèques tierces_ (_third party libraries_)
* Une bibliothèque est organisé en packages

== Utilisation d'un bibliothèque tierce
. Récupérer la bibliothèque
** manuellement (téléchargement du `jar`)
** automatiquement (outils de gestion des dépendances comme _maven_ ou _gradle_)
. Inclure la bibliothèque dans le projet
** le `CLASSPATH` doit être modifié pour faire référence aux archives (`jar` en général) de la bibliothèque
. Consulter l'interface de la bibliothèque
** toute bibliothèque Java est distribuée avec sa documentation au format _javadoc_
. Importer les modules nécessaires dans les fichiers sources
** l'utilisation d'une classe de la bibliothèque nécessite d'importer le package Java adéquat

== Exemple : utilisation de la bibliothèque _Apache Commons Math_
. Télécharger et décompresser le fichier http://commons.apache.org/proper/commons-math/download_math.cgi[commons-math3-3.6.1-bin.tar.gz]
+
[source,bash,indent=0]
----
$ wget -c https://downloads.apache.org//commons/math/binaries/commons-math3-3.6.1-bin.tar.gz -O - | tar -xz
$ ls commons-math3-3.6.1
~/commons-math3-3.6.1 $ ls
commons-math3-3.6.1.jar               commons-math3-3.6.1-tools.jar
commons-math3-3.6.1-javadoc.jar       docs/
commons-math3-3.6.1-sources.jar       LICENSE.txt
commons-math3-3.6.1-tests.jar         NOTICE.txt
commons-math3-3.6.1-test-sources.jar  RELEASE-NOTES.txt
----
. Ajouter la bibliothèque au projet (IDE ou outil de _build_)
+
[source,xml,indent=0]
----
<!-- Avec maven -->
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-math3</artifactId>
    <version>3.6.1</version>
</dependency>
----
. Importer les classes des packages nécessaires
+
[source,java,indent=0]
----
import org.apache.commons.math3.fraction.Fraction;

public class Main {
    public static void main(String[] args) {
        Fraction f = new Fraction(1, 3);
        System.out.println(f);
    }
}
----
. Compiler en précisant la bibliothèque dans le CLASSPATH (en ligne de commande)
+
[source,bash,indent=0]
----
$ javac -cp commons-math3-3.6.1/commons-math3-3.6.1.jar Main.java
----
. Éxécuter en précisant la bibliothèque dans le CLASSPATH (en ligne de commande)
+
[source,bash,indent=0]
----
$ java -cp commons-math3-3.6.1/commons-math3-3.6.1.jar Main
----
