= Langage Java
ifndef::masterdoc[]
include::meta.adoc[]
include::attributes.adoc[]
endif::masterdoc[]

== Le langage Java
* Le https://fr.wikipedia.org/wiki/Java_(langage)[langage Java] est un langage de programmation orienté objet développé chez https://fr.wikipedia.org/wiki/Sun_Microsystems[Sun Microsystems] (racheté par Oracle en 2009) et lancé officiellement en 1995
+
NOTE: http://www.oracle.com/technetwork/java/langenv-140151.html[The Java Language Environment: A White Paper], James Gosling, 1996.
* https://docs.oracle.com/en/java/index.html[Différentes éditions] de la plateforme Java sont disponibles
** _Java SE_ pour les postes de travail,
** _Java EE_ pour les serveurs, et
** _Java Embedded_ pour les terminaux à ressources contraintes.
+
NOTE: Cet aide-mémoire se focalise sur Java SE
* Depuis 2006, le code source de Java est _libre_ et _open source_ et l'implémentation de référence se nomme https://openjdk.java.net/[OpenJDK]
* Depuis 2019 et suite à un changement de licence et de modèle de support opéré par Oracle, plusieurs distributions du JDK sont apparues (https://adoptopenjdk.net/[AdoptOpenJDK], https://aws.amazon.com/fr/corretto/[Amazon Corretto], https://www.graalvm.org/[GraalVM], https://www.azul.com/downloads/zulu-community/[Zulu OpenJDK])

== JRE et JDK
* Le _Java Runtime Environment_ (JRE) fournit la _machine virtuelle Java_, les bibliothèques et d'autres composants nécessaires pour l'*exécution* de programmes Java
+
NOTE: https://docs.oracle.com/javase/specs/index.html[Java Language and Virtual Machine Specifications]
* Le _Java Development Kit_ (JDK) fournit le JRE ainsi qu'un ensemble d'outils pour le développement d'applications
+
NOTE: https://docs.oracle.com/en/java/javase/14/docs/specs/man/index.html[JDK Tool Specifications]

== Compilation et interprétation
* Le langage Java est à la fois _interprété_ et _compilé_
* Un fichier source (`.java`) est compilé en un langage intermédiaire appelé _bytecode_ (`.class`)
* Ce bytecode est ensuite interprété par la _machine virtuelle Java_

[ditaa, "java-compil-exec",svg]
----
 +-----------+    +-------------+    +-----------+    +------------+    +-----------+
 |           |    | Compilateur |    |           |    | Machine    |    | Exécution |
 | Prog.java |--->| (javac)     |--->| Prog.class|--->| Virtuelle  |--->| de Prog   |
 |        {d}|    | cYEL        |    |        {d}|    | (java) cBLU|    |           |
 +-----------+    +-------------+    +-----------+    +------------+    +-----------+
----

NOTE: https://docs.oracle.com/javase/tutorial/getStarted/intro/definition.html[About the Java Technology]

=== Compilation en ligne de commande (JDK)
.Le compilateur https://docs.oracle.com/en/java/javase/14/docs/specs/man/javac.html[`javac`] génère le _bytecode_ en ligne de commande.
[source,bash,indent=0]
----
$ javac <options> <fichiers source>
----

.Quelques options importantes
[horizontal]
`--class-path`|`-classpath`|`-cp`:: fixe le chemin de recherche des classes compilées (_Classpath_)
`-d`:: fixe le répertoire de destination pour les classes compilées
`-encoding`:: précise l'encodage des fichiers sources ("UTF-8", ...)
`-g`|`-g:none`:: gère les informations pour le débogage
`--source`|`-source`:: précise la version des fichiers sources (`8`, ..., `11`, ...)
`-sourcepath`:: fixe le chemin de recherche des sources
`--target`|`-target`:: précise la version de la VM cible (`8`, ..., `11`, ...)

.Compilation séparant les sources des fichiers compilés
[source,bash,indent=0]
----
$ javac -sourcepath src \ #<1>
        -source 11 \ #<2>
        -d classes \ #<3>
        -classpath classes \ #<4>
        -g \ #<5>
        src/MonApplication.java #<6>
----
<1> les sources se trouvent dans le répertoire `src`
<2> les fichiers sources sont conformes à la version 11 de Java
<3> les fichiers compilés `.class` doivent être placés dans le répertoire `classes`
<4> le réperoire `classes` est ajouté au _Classpath_
<5> les informations de débogage sont intégrées
<6> le programme principal se trouve dans `src/MonApplication.java`

NOTE: https://docs.oracle.com/en/java/javase/14/docs/specs/man/javac.html[The javac Command]

=== Exécution en ligne de commande (JRE)
.https://docs.oracle.com/en/java/javase/14/docs/specs/man/java.html[`java`] permet d'exécuter le programme
[source,bash,indent=0]
----
$ java [-options] class [args...]
$ java [-options] -jar jarfile [args...]
----

.Quelques options importantes
[horizontal]
`class`:: le nom de la classe contenant le programme principal (le `.class` doit pouvoir être trouvé dans le _CLASSPATH_)
`--class-path`|`-classpath`|`-cp`:: fixe le chemin de recherche des classes compilées
`-jar`:: exécute un programme encapsulé dans un fichier `jar`

.Exécution}
[source,bash,indent=0]
----
$ java -cp classes \ #<1>
       MonApplication #<2>
----
<1> ajoute le répertoire `classes` au_CLASSPATH_
<2> l'exécution débutera par la méthode `main` de la classe `MonApplication`

NOTE: https://docs.oracle.com/en/java/javase/14/docs/specs/man/java.html[The java Command]

== _Classpath_
* Le _Classpath_ précise la liste des bibliothèques ou des classes compilées utilisées par l'environnement Java
* Le compilateur et la machine virtuelle ont besoin d'avoir accès aux classes compilées
* Il peut être défini en ligne de commande ou par la variable d'environnement `CLASSPATH`

NOTE: https://docs.oracle.com/javase/tutorial/essential/environment/paths.html[PATH and CLASSPATH] et {jlsurl}/jls-12.html[Execution]

== Les indispensables pour développer en Java
[TIP]
====
* Adopter un _style de codage_ comme le https://google.github.io/styleguide/javaguide.html[Google Java Style Guide] et vérifier les violations avec https://checkstyle.sourceforge.io/[Checkstyle]
* Utiliser un _système de gestion de versions_ (https://git-scm.com/[git]) et une _forge logicielle_ (https://github.com/[github], https://bitbucket.org/[bitbucket], https://gitlab.com/[gitlab])
* Faire des _tests unitaires_ (https://junit.org/junit5/[JUnit])
* Automatiser les tâches répétitives (https://maven.apache.org/[Maven], https://gradle.org/[Gradle])
====

== Références
=== Webographie
* https://docs.oracle.com/en/java/javase/index.html[Java Platform, Standard Edition Documentation]
* https://docs.oracle.com/en/java/javase/15/docs/api/index.html[Java API]
* http://docs.oracle.com/javase/tutorial/[_The Java Tutorials_]
* Aide-mémoire :
https://dzone.com/asset/download/51834[Core Java],
https://www.azul.com/files/12992683-dzone-refcard318-java13-v2.pdf[Java 13],
https://www.azul.com/files/13301143-dzone-refcard-318-java-14-v2.pdf[Java 14]
* https://blog.jetbrains.com/?s=Java+Annotated+Monthly[Java Annotated Monthly] (blog)

=== Bibliographie (apprentissage)
* *David J. Barnes & Michael Kölling*. http://www.bluej.org/objects-first/[_Objects First with Java_].  Pearson. 2016.
* *Marc Loy, Patrick Niemeyer, Daniel Leuck*, https://www.oreilly.com/library/view/learning-java-5th/9781492056263/[Learning Java: An Introduction to Real-world Programming With Java]. O'Reilly Media. 2020.

=== Bibliographie (Perfectionnement)
* *Joshua Bloch*. _Effective Java 3rd Edition_. Addison-Wesley Professional. 2017.
* *Kevlin Henney & Trisha Gee*, https://www.oreilly.com/library/view/97-things-every/9781491952689/[97 Things Every Java Programmer Should Know]. 2020.
* *Joshua Bloch & Neal Gafter*. http://www.javapuzzlers.com/[_Java Puzzlers_].  Addison-Wesley. 2005.
* *Cay S. Horstmann & Gary Cornell*, https://horstmann.com/corejava/index.html[Core Java]. Prentice Hall. 2015.
